networks:
  web:
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks: [web]
  migrate:
    image: ghcr.io/lizaq94/exerciselog-app-api:main-159241a
    command: npx prisma migrate deploy
    env_file: .env.prod
    networks: [web]
  app:
    image: ghcr.io/lizaq94/exerciselog-app-api:main-159241a
    restart: unless-stopped
    env_file: .env.prod
    networks: [web]
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  caddy_data:
  caddy_config: