import { IsArray, ValidateNested, ArrayMinSize } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';
import { AiTrainingPlanDto } from './ai-training-plan.dto';

export class AiResponseDto {
  @ApiProperty({
    description: 'List of training plans generated by AI',
    type: [AiTrainingPlanDto],
  })
  @IsArray()
  @ArrayMinSize(1, { message: 'AI must return at least one training plan' })
  @ValidateNested({ each: true })
  @Type(() => AiTrainingPlanDto)
  trainingPlans: AiTrainingPlanDto[];
}
